version: '3.9'

services:
  nextapp:
    container_name: nextapp
    image: nextapp
    build: .
    ports:
      - "32769:3000"
    volumes:
      - ./public/assets:/app/public/assets
      - ./next-cache:/app/.next/cache

