version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - "3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
    networks:
      - my-network
    volumes:
      # - ./public/assets/images:/app/public/assets/images
      - ./:/app
networks:
  my-network:
