version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
    networks:
      - my-network

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - "8080:80" # Change this line to use port 8080 on the host
  #   depends_on:
  #     - app
  #   networks:
  #     - my-network

networks:
  my-network:
